[project]
name = "dev"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "samjtro", email = "hi@samjtro.com"},
]
dependencies = ["rn4s>=0.1.0"]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
